name: Release
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
      with:
        # Reproduce the exact commit hash value
        fetch-depth: 0
        ref: ${{ github.event.pull_request.head.sha }}
    - run: echo "SOURCE_DATE_EPOCH=$(git log -1 --pretty=%ct)" >> $GITHUB_ENV
    - uses: docker/setup-buildx-action@v2
    - name: Cache var-cache-apt
      uses: actions/cache@v3
      with:
        path: var-cache-apt
        key: var-cache-apt-${{ hashFiles('Containerfile.cross') }}
    - name: Cache var-lib-apt
      uses: actions/cache@v3
      with:
        path: var-lib-apt
        key: var-lib-apt-${{ hashFiles('Containerfile.cross') }}
    - name: inject var-cache-apt into docker
      uses: reproducible-containers/buildkit-cache-dance@v2.1.2
      with:
        cache-source: var-cache-apt
        cache-target: /var/cache/apt
    - name: inject var-lib-apt into docker
      uses: reproducible-containers/buildkit-cache-dance@v2.1.2
      with:
        cache-source: var-lib-apt
        cache-target: /var/lib/apt
    - name: "Build binaries from Containerfile.cross"
      run: docker buildx build -o /tmp/fuse-overlayfs-builds --build-arg SOURCE_DATE_EPOCH --platform=amd64,arm64,arm,s390x,ppc64le,riscv64 -f Containerfile.cross .
    - name: "Create dist"
      run: |
        mkdir -p dist
        mv /tmp/fuse-overlayfs-builds/linux_amd64/fuse-overlayfs dist/fuse-overlayfs-x86_64
    - name: Upload artifact to release
      uses: actions/upload-artifact@v1.0.0
      with:
        name: fuse-overlayfs-x86_64
        path: 'dist'
    - name: Compute Short SHA
      id: ssha
      run: |
        echo "ssha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
    outputs:
      ssha: ${{ steps.ssha.outputs.ssha }}

  release:
    permissions: write-all
    needs: [build]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/download-artifact@v1
        with:
          name: fuse-overlayfs-x86_64

      - name: release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          title: Continuous ${{ needs.build.outputs.ssha }}
          automatic_release_tag: ${{ needs.build.outputs.ssha }}
          prerelease: false
          draft: false
          files: |
            fuse-overlayfs-x86_64
          repo_token: ${{ secrets.GITHUB_TOKEN }}
